### ISSUE TITLE
custom food serving size in edit foods?

### ISSUE THREAD

**Issue by nutpantz** [brandonp2412/FitBook#1]
In diary you can choose your serving size by cups, grams, etc
(I assume it's used to calculation size for calories)
But i don't see where in foods>edit foods you can set the serving by cups or grams etc.

You can put it in the description, but does that allow for calories calculation? 

I primary use only custom food as i don't have a hugely varied diet 95% of the time.

**Comment by brandonp2412** [comment]
Yeah its a bit confusing I put it in the other fields. Its "Serving weight 1". Only made all those fields like that because MyFoodData has a bazillion fields I didn't want to map myself

**Comment by nutpantz** [comment]
You can't pick the measurement in foods edit like you can in diary.

**Comment by brandonp2412** [comment]
Hmm it might be a bit more confusing to do something like that. I'll have to think about it for a while. All the fields on "Foods" are per 100g (another thing i'm not sure how to make this more clear, something in the title?). So if I had a custom unit for serving size I just wonder how that would work with calculating all the other fields

**Comment by brandonp2412** [comment]
What about i move "Serving weight 1" and "Serving description 1" above "Show other fields", make them "Serving amount" and "Serving unit". Then whenever I do servings calculations, I run my conversion function to be 100g

**Comment by nutpantz** [comment]
Well too be honest i think most people use volume over weight for serving size. (I know that weight is the better way to measure, but never do)

There needs to be a way to convert the food calories\weight\volume to the preferred serving size in diary.  
The way i have seen it done before is you put in the serving size by weight AND volume (ie 50 calories \ .33 cups \34 grams) (and could choose cups\liters\ml or oz\gram\Kg) and when you do your diary the serving size you eat is converted to calories and nutrition

But i don't know how complicated that is too implement. (I know metric vs imperial US vs UK is not fun(just go metric everything lol)

Personally i would like a setting to "always show" above other fields various things (but that would be s different issue) in settings. So i can pick and choose what is always visible.

**Comment by anddam** [comment]
> All the fields on "Foods" are per 100g (another thing i'm not sure how to make this more clear, something in the title?). So if I had a custom unit for serving size I just wonder how that would work with calculating all the other fields

Either add a label on top "all measurements are per 100 g" or add ` / hg` to the individual units of measure, e.g. 

    Energy (kcal / hg)
    Energy (kJ / hg)
    Proteing (g / hg)

(joule symbol is capital J).

I agree you should just move the serving unit and size in the top section of the view, so they are always visible, and maybe make default serving weight 100 g rather than 1 g.

**Comment by nutpantz** [comment]
A calorie and nutrition tracking app that cannot do the conversion to the serving being consumed is very cumbersome. 
Having to do the math from the product label to only 100g servings (which i have never seen on a product label yet) is even more cumbersome.

**Comment by brandonp2412** [comment]
> A calorie and nutrition tracking app that cannot do the conversion to the serving being consumed is very cumbersome. Having to do the math from the product label to only 100g servings (which i have never seen on a product label yet) is even more cumbersome.
> […](#)
> On May 28, 2024 1:08:54 PM PDT, anddam ***@***.***> wrote: > All the fields on "Foods" are per 100g (another thing i'm not sure how to make this more clear, something in the title?). So if I had a custom unit for serving size I just wonder how that would work with calculating all the other fields Either add a label on top "all measurements are per 100 g" or add ` / hg` to the individual units of measure, e.g. Energy (kcal / hg) Energy (kJ / hg) Proteing (g / hg) (joule symbol is capital J). I agree you should just move the serving unit and size in the top section of the view, so they are always visible, and maybe make default serving weight 100 g rather than 1 g. -- Reply to this email directly or view it on GitHub: [#1 (comment)](https://github.com/brandonp2412/FitBook/issues/1#issuecomment-2136022393) You are receiving this because you authored the thread. Message ID: ***@***.***>

Do other countries put the nutrition facts as per serving and not have a column for per 100g?

**Comment by nutpantz** [comment]
<https://www.fda.gov/food/nutrition-education-resources-materials/nutrition-facts-label>

North America does not have a column for 100g

**Comment by anddam** [comment]
> Do other countries put the nutrition facts as per serving and not have a column for per 100g? Im from NZ so every food label i've read has it as per serving and then per 100g

That is the ruling in EU as well, manufacturer can put additional declarations columns (as per serving) but the 100 g or ml [is a requirement](https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02011R1169-20180101#tocId225).

**Comment by brandonp2412** [comment]
@nutpantz the calculation wasn't right for servings using entries, you should be able to enter the stuff in food now as if it's per serving (if you said the serving). Tell me if it's working OK for  you.

As for other units as a serving size, is there any authoritative source saying what units the USA are allowed to have in the serving sizes? Or is it always grams?

**Comment by nutpantz** [comment]
Setting the serving seems to work, however i don't know if the conversion is correct. 1 metric cup should be 250ml, but setting the custom food to cups and diary to ml it appears that diary has 200ml as a cup (or at least i need to set diary ml to 200 to match calories in custom foods set in cups)

I don't think the USA has a set serving unit.
It could be grams, cups, bags, teaspoons , even pounds,  (usually cups or grams mostly i think)
I think 99% of companies use what looks best for their product not what is the usual serving people eat. (Who eats 2\3 of a cup of chips)
(US cup is 236ml usually i think)
