### ISSUE TITLE
[Feature Request]Custom tags for food

### ISSUE THREAD

**Issue by Mistymimi** [brandonp2412/FitBook#17]
Being able to tag a food as being from specific places could be useful. For example someone could mark one food as 'fastfood' and 'Mcdonalds' or another food as 'homecooked' and 'Vegetarian'. If someone's on a roadtrip filtering fastfood entries you've made before can be helpful or if you quickly need to look over vegetarian meals you've prepared because a vegetarian friend is coming over that can save a lot of time.

**Comment by brandonp2412** [comment]
This partly exists as "Food group"

![image](https://github.com/brandonp2412/FitBook/assets/14083541/03c7298c-3c46-4849-a601-cc939e3db014)

We could pivot this issue to be about a tag filter button in the dropdown menu?

**Comment by Mistymimi** [comment]
There's a little bit of ambiguity as to what you mean but sure.
