### ISSUE TITLE
Removing baby food from existing data

### ISSUE THREAD

**Issue by Mistymimi** [brandonp2412/FitBook#18]
Having baby food in data entries may make some uneducated parents think restricting calories their baby is a good idea when that can be extremely dangerous. I find the possibility unlikely but I think if it saved just one the change would be worth it. Additionally even if that never happens the removal would make existing data entries more useful to almost all if not all users.

**Comment by brandonp2412** [comment]
This app is not specifically about restricting calories. I am also not interested in the ethical implications of counting babies calories. All the foods included are simply what MyFoodData have in their export.
