### ISSUE TITLE
[Feature request] see serving sizes on diary page

### ISSUE THREAD

**Issue by Mistymimi** [brandonp2412/FitBook#21]
Currently when you look at your diary entries you have to select each individual entry to see the number of servings. It would be nice to be able to see them at a glance without going into each entry.

**Comment by brandonp2412** [comment]
I don't think i'll implement this since there is already enough of information on the diary list page.

However I'm going to add it to the foods list.

**Comment by Mistymimi** [comment]
I wrote the title wrong I meant to say number of servings rather than serving sizes. So if you set taco to being two servings in an entry it would show x2 or something equivalent on the diary page.
