### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [brandonp2412/FitBook#23]
https://monitor.f-droid.org/builds/log/com.starry.myne/391#site-footer

Only the zip metadata is different.

**Comment by linsui** [comment]
New versions are reproducible. Do you know why?

**Comment by brandonp2412** [comment]
Which versions are failing and what's the f-droid pipeline link?

**Comment by linsui** [comment]
Ah, my mistake. FitBook build failed because background_fetch is not needed anymore. I have fixed it. Sorry!
