### ISSUE TITLE
[Feature Request] Add setting for weight units

### ISSUE THREAD

**Issue by marcus-quincy** [brandonp2412/FitBook#24]
I think it would be useful to add a setting for preferred unit for body weight. I use pounds but the app currently defaults to kg whenever I enter my weight. I think this would look similar to how you can set the Food unit in settings

I should have some time this weekend and would be happy to work on it :)

**Comment by brandonp2412** [comment]
Rather than a setting i think the app should remember the previous entry and auto-fill it instead
