### ISSUE TITLE
Add a translation service

### ISSUE THREAD

**Issue by balaraz** [brandonp2412/FitBook#27]
Add the ability to translate your app into other languages. There are special services for this, for example, [Weblate](https://weblate.org).

**Comment by brandonp2412** [comment]
I have not enjoyed working with source codes that use translation services in the past. However I am open to reading any PRs that include translation services. Also this project is put on the f-droid store so every service used needs to be [FOSS](https://www.gnu.org/philosophy/floss-and-foss.en.html)

**Comment by balaraz** [comment]
`Weblate` is a FOSS and it have many servers.
`F-Droid` requires that the application itself does not access third-party services, and what is used during development is not important. There are many programs that use Weblate or other closed translation services.

Sometimes it's hard for translators to understand the file structure of each project, and it's not convenient.
I'm not a mobile app developer (Android/IOS) and I don't have Android Studio.
