### ISSUE TITLE
[Feature Request] Add Container Transform Transitions for FAB

### ISSUE THREAD

**Issue by kwe92** [brandonp2412/FitBook#34]
Hello,

I wanted to contribute to your project and update the navigation for your FAB.

The idea was inspired by the material motion system docs:

https://m2.material.io/design/motion/the-motion-system.html#transition-patterns

I tried to create a draft PR to show you an example but my permissions were denied.

**Comment by brandonp2412** [comment]
I haven't restricted PRs

**Comment by kwe92** [comment]
My apologies, I cloned the repo directly to run the app and didn't make a fork afterward.

I have a PR up for my suggested U.I. change #35.
