### ISSUE TITLE
FitBook at OpenAOPK

### ISSUE THREAD

**Issue by mobilenetworkltd** [brandonp2412/FitBook#4]
Hey,

I'm running a open source repo for Android apps at https://www.openapk.net/ and I would like to have FitBook listed in the repo. Please review the listing at https://www.openapk.net/fitbook/com.presley.fit_book/

It is hooked to your GitHub repo so all the updates are automatically pushed to OpenAPK. Let me know if its ok !

If you are interested you can link to it and use our download banners ( https://www.openapk.net/images/openapk-badge.png )

**Comment by brandonp2412** [comment]
Looks good my brother.
