### ISSUE TITLE
[Feature Request] Add time to entry to allow entering everything from the day

### ISSUE THREAD

**Issue by natrius** [brandonp2412/FitBook#9]
And make it possible to change later when editing that entry as well. Also - sort entries by time as well. If i move something from evening (accidentaly forgot to change time) to morning (actual time i ate) i would like to see it reflected in the app as well. 

Btw. thanks for the app! I know two other, Waistline is mighty but complicated and Energize is simple but develpment slowed down unfortunately.

**Comment by brandonp2412** [comment]
Time is editable if your date format includes the time

**Comment by natrius** [comment]
Oh, i missed that. Maybe rename the setting field to "Date and time format" and just change the example behind it?
